"""TektosSimulator — test-only harness for Stage-2.4 exit gate (ADR-035).

Publishes :class:`~ports.trace_feed.TraceEvent` instances with
``plugin="tektos"`` on an injected :class:`~ports.trace_feed.TraceFeedPort`.

The simulator exists to prove Stage 2.4's cross-plugin composition:

    Tektos-side trace  ─▶  TraceFeedPort  ─▶  Phrouros  ─▶  event bus
                                                            │
                                                            ▼
                                             AnomalyBridge (Praxis)
                                                            │
                                                            ▼
                                             APEX.propose(HUMAN_REQUIRED)
                                                            │
                                                            ▼
                                             NotificationPort.deliver_algedonic

It does **not** ship any Tektos business logic, planner, LLM adapter,
or panel. Real Stage-3 Tektos will emit trace events from its actual
tool-call execution loop; the simulator is a stand-in until then.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from ports.trace_feed import TraceEvent, TraceFeedPort

__all__ = ["TektosSimulator"]


TEKTOS_PLUGIN_NAME = "tektos"


def _new_id() -> str:
    """UUID4 hex string. Local helper to avoid importing Phrouros."""
    return uuid.uuid4().hex


@dataclass(slots=True)
class TektosSimulator:
    """Publish synthetic Tektos trace events on a TraceFeedPort.

    Composition is cheap and side-effect-free — nothing happens until
    one of the ``simulate_*`` methods is awaited.

    Attributes:
        trace_feed: The :class:`TraceFeedPort` adapter events are
            published to. Same adapter Phrouros subscribes to in the
            Stage-2.4 exit-gate scenario.
    """

    trace_feed: TraceFeedPort

    async def simulate_unauthorized_call(
        self,
        *,
        tool_name: str,
        trace_id: str | None = None,
        occurred_at: datetime | None = None,
    ) -> TraceEvent:
        """Publish a single :class:`TraceEvent` for an unauthorized tool.

        Args:
            tool_name: The (deliberately-unauthorized) tool identifier
                the simulated Tektos agent attempted to invoke.
            trace_id: Optional caller-supplied trace id. Autogenerated
                UUID4 hex when omitted.
            occurred_at: Optional tz-aware timestamp. Defaults to now.

        Returns:
            The :class:`TraceEvent` that was published (already sent to
            the feed; return value is for test assertions).
        """
        event = self._build_event(
            tool_name=tool_name,
            trace_id=trace_id,
            occurred_at=occurred_at,
        )
        await self.trace_feed.publish(event)
        return event

    async def simulate_authorized_call(
        self,
        *,
        tool_name: str,
        trace_id: str | None = None,
        occurred_at: datetime | None = None,
    ) -> TraceEvent:
        """Publish a single :class:`TraceEvent`.

        The method name is a hint to test authors: pair this with an
        allowlist that contains ``tool_name`` to prove the detector
        does **not** fire on authorized calls. The event payload is
        identical to :meth:`simulate_unauthorized_call`; only the
        caller's allowlist configuration decides authorization.
        """
        event = self._build_event(
            tool_name=tool_name,
            trace_id=trace_id,
            occurred_at=occurred_at,
        )
        await self.trace_feed.publish(event)
        return event

    async def simulate_loop(
        self,
        *,
        tool_name: str,
        count: int,
        window_seconds: float,
        trace_id: str | None = None,
    ) -> list[TraceEvent]:
        """Publish ``count`` identical events across ``window_seconds``.

        Used by Stage-2.4 tests that reuse LoopDetector (ADR-035 Q2=C)
        to prove the detector-tuple seam supports two detectors firing
        concurrently on the same trace feed.

        Args:
            tool_name: Tool identifier repeated across all events.
            count: Number of events to publish. Must be ``>= 1``.
            window_seconds: Total wall-clock span across which the
                event ``occurred_at`` values are evenly distributed.
                Must be ``>= 0``.
            trace_id: Optional caller-supplied trace id (shared by
                every event so LoopDetector can correlate them).

        Returns:
            The ordered list of published :class:`TraceEvent` instances.
        """
        if count < 1:
            raise ValueError("count must be >= 1")
        if window_seconds < 0:
            raise ValueError("window_seconds must be >= 0")

        trace = trace_id if trace_id is not None else _new_id()
        base = datetime.now(timezone.utc)
        step = (
            timedelta(seconds=window_seconds / max(count - 1, 1))
            if count > 1
            else timedelta(0)
        )

        events: list[TraceEvent] = []
        for i in range(count):
            occurred = base + (step * i)
            event = self._build_event(
                tool_name=tool_name,
                trace_id=trace,
                occurred_at=occurred,
            )
            await self.trace_feed.publish(event)
            events.append(event)
        return events

    # ── Internals ──────────────────────────────────────────────────────

    def _build_event(
        self,
        *,
        tool_name: str,
        trace_id: str | None,
        occurred_at: datetime | None,
    ) -> TraceEvent:
        return TraceEvent(
            event_id=_new_id(),
            occurred_at=occurred_at
            if occurred_at is not None
            else datetime.now(timezone.utc),
            plugin=TEKTOS_PLUGIN_NAME,
            tool_name=tool_name,
            trace_id=trace_id if trace_id is not None else _new_id(),
            span_id=_new_id(),
        )
